$hangars = [
    [
      'num'   => 'MAIN HANGAR',
      'title' => 'Vintage Aircraft',
      'sub'   => 'De Havilland Tiger Moth &bull; Chipmunk TMK.10 &bull; SLAF manufactured aircraft',
      'desc'  => 'Collection of vintage aircraft used by SLAF since inception. Fully restored flying legends. Also houses four additional hangars with picture galleries, vehicles, arms, ordnance, uniforms and a mini-cinema.',
      'img'   => 'https://images.unsplash.com/photo-1556388158-158ea5ccacbd?w=900&q=80',
      'alt'   => 'Main Hangar',
    ],
    [
      'num'   => 'OUTDOOR EXHIBITS',
      'title' => 'Aircraft &amp; Artillery',
      'sub'   => 'LTTE aircraft shot down by SLAF &bull; Wreckage &amp; vehicles &bull; 130mm howitzer',
      'desc'  => 'Positioned on professionally landscaped area adjacent to hangar complex. A powerful testimony to the dedication and surgical precision of the Sri Lanka Air Force.',
      'img'   => 'https://images.unsplash.com/photo-1556388158-158ea5ccacbd?w=900&q=80',
      'alt'   => 'Outdoor Exhibits',
    ],
    [
      'num'   => 'HANGAR NO. 01',
      'title' => 'Aviation History',
      'sub'   => 'Photos depicting past &amp; present of SLAF',
      'desc'  => 'Houses an extensive photographic record depicting the past and present of the SLAF and the rich aviation history of Sri Lanka.',
      'img'   => 'https://images.unsplash.com/photo-1556388158-158ea5ccacbd?w=900&q=80',
      'alt'   => 'Hangar No.01',
    ],
    [
      'num'   => 'HANGAR NO. 02',
      'title' => 'General Exhibits',
      'sub'   => 'Linik simulator &bull; Right Flyer &bull; Air defence guns &bull; Air Force flags',
      'desc'  => 'General exhibits which have seen utility in the SLAF over the years. Features the linik simulator model, right flyer, air defence guns and various flags of Air Force units.',
      'img'   => 'https://images.unsplash.com/photo-1556388158-158ea5ccacbd?w=900&q=80',
      'alt'   => 'Hangar No.02',
    ],
    [
      'num'   => 'HANGAR NO. 03',
      'title' => 'Civil Engineering',
      'sub'   => 'Complete civil engineering exhibits',
      'desc'  => 'The No. 3 Hangar is dedicated to Civil Engineering exhibits, showcasing the infrastructure development and engineering heritage of the SLAF throughout its history.',
      'img'   => 'https://images.unsplash.com/photo-1556388158-158ea5ccacbd?w=900&q=80',
      'alt'   => 'Hangar No.03',
    ],
    [
      'num'   => 'HANGAR NO. 04',
      'title' => 'Vehicles',
      'sub'   => 'Complete Vehicle exhibits',
      'desc'  => 'The No. 4 Hangar displays different types of vehicles used within Sri Lanka Air Force from the days of Royal Air Force.',
      'img'   => 'https://images.unsplash.com/photo-1556388158-158ea5ccacbd?w=900&q=80',
      'alt'   => 'Hangar No.04',
    ],
    [
      'num'   => 'HANGAR NO. 05',
      'title' => 'Engine Bay',
      'sub'   => 'Complete Engine Bay exhibits',
      'desc'  => 'The No. 5 Hangar houses an Engine Bay consisting of all types of Aircraft Engines from vintage aircraft.',
      'img'   => 'https://images.unsplash.com/photo-1556388158-158ea5ccacbd?w=900&q=80',
      'alt'   => 'Hangar No.05',
    ],
    [   
      'num'   => 'HANGAR NO. 06',
      'title' => 'THE KNOWLEDGE HUB',
      'sub'   => 'The Command Research Library &ldquo;The Knowledge Hub&rdquo;',
      'desc'  => 'The No. 6 Hangar was declared open by former Commander Air Marshal Harsha Abeywickrama on 11 March 2013. A unique place for all knowledge hunters in aviation, with old collections of books on aircraft operated by the SLAF and Royal Ceylon Air Force.',
      'img'   => 'https://images.unsplash.com/photo-1556388158-158ea5ccacbd?w=900&q=80',
      'alt'   => 'Hangar No.06',
    ],
  ];